### ISSUE TITLE
How do I solve the following harp errors on my project?

### ISSUE THREAD

**Issue by LaVie-environment** [LaVie-environment/Harp#1]
Please, I ran "harp version" command to get the Harp version on my system, but it prompted the following error on my PowerShell.

PS C:\> harp version
harp : C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\node-
sass\lib\binding.js:15
At line:1 char:1
+ harp version
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\GACHIO...b\binding.js:15 
   :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
      throw new Error(errors.missingBinary());
      ^
Error: Missing binding C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\no
de_modules\node-sass\vendor\win32-x64-64\binding.node
Node Sass could not find a binding for your current environment: Windows 
64-bit with Node.js 10.x
Found bindings for the following environments:
  - Windows 64-bit with Node.js 8.x
This usually happens because your environment has changed since running `npm 
install`.
Run `npm rebuild node-sass` to download the binding for your current 
environment.
    at module.exports (C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\no
de_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:\Users\GACHIO\AppData\Roaming\npm\node_modules\har
p\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\GACHIO\AppData\Roaming\npm\node_modules\har
p\node_modules\terraform\lib\stylesheet\processors\scss.js:1:74)

**Comment by LaVie-environment** [comment]
gyp verb install version is good
    gyp verb get node dir target node version installed: 11.10.0
    gyp verb build dir attempting to create "build" dir: C:\Users\GACHIO\AppData\Roa
    ming\npm\node_modules\harp\node_modules\node-sass\build
    gyp verb build dir "build" dir needed to be created? C:\Users\GACHIO\AppData\Roa
    ming\npm\node_modules\harp\node_modules\node-sass\build
    gyp verb build/config.gypi creating config file
    gyp verb build/config.gypi writing out config file: C:\Users\GACHIO\AppData\Roam
    ing\npm\node_modules\harp\node_modules\node-sass\build\config.gypi
    gyp verb config.gypi checking for gypi file: C:\Users\GACHIO\AppData\Roaming\npm
    \node_modules\harp\node_modules\node-sass\config.gypi
    gyp verb common.gypi checking for gypi file: C:\Users\GACHIO\AppData\Roaming\npm
    \node_modules\harp\node_modules\node-sass\common.gypi
    gyp verb gyp gyp format was not specified; forcing "msvs"
    gyp info spawn C:\Users\GACHIO\.windows-build-tools\python27\python.exe
    gyp info spawn args [ 'C:\\Users\\GACHIO\\AppData\\Roaming\\npm\\node_modules\\h
    arp\\node_modules\\node-gyp\\gyp\\gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'msvs',
    gyp info spawn args   '-G',
    gyp info spawn args   'msvs_version=2015',
    gyp info spawn args   '-I',
    gyp info spawn args   'C:\\Users\\GACHIO\\AppData\\Roaming\\npm\\node_modules\\h
    arp\\node_modules\\node-sass\\build\\config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   'C:\\Users\\GACHIO\\AppData\\Roaming\\npm\\node_modules\\h
    arp\\node_modules\\node-gyp\\addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   'C:\\Users\\GACHIO\\.node-gyp\\11.10.0\\include\\node\\com
    mon.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=C:\\Users\\GACHIO\\.node-gyp\\11.10.0',
    gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\GACHIO\\AppData\\Roaming\\npm\\
    node_modules\\harp\\node_modules\\node-gyp',
    gyp info spawn args   '-Dnode_lib_file=C:\\Users\\GACHIO\\.node-gyp\\11.10.0\\<(
    target_arch)\\node.lib',
    gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\GACHIO\\AppData\\Roaming\\np
    m\\node_modules\\harp\\node_modules\\node-sass',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'C:\\Users\\GACHIO\\AppData\\Roaming\\npm\\node_modules\\h
    arp\\node_modules\\node-sass\\build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp verb command build []
    gyp verb build type Release
    gyp verb architecture x64
    gyp verb node dev dir C:\Users\GACHIO\.node-gyp\11.10.0
    gyp verb found first Solution file build/binding.sln
    gyp verb could not find "msbuild.exe" in PATH - finding location in registry
    gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
    gyp info spawn args [ 'build/binding.sln',
    gyp info spawn args   '/nologo',
    gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
    Building the projects in this solution one at a time. To enable parallel build,
    please add the "/m" switch.
    Build started 2/22/2019 11:01:00 PM.
    Project "C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\nod
    e-sass\build\binding.sln" on node 1 (default targets).
    ValidateSolutionConfiguration:
      Building solution configuration "Release|x64".
    Project "C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\nod
    e-sass\build\binding.sln" (1) is building "C:\Users\GACHIO\AppData\Roaming\npm\
    node_modules\harp\node_modules\node-sass\build\binding.vcxproj" (2) on node 1 (
    default targets).
    PrepareForBuild:
      Creating directory "Release\obj\binding\".
      Creating directory "Release\obj\binding\binding.tlog\".
    InitializeBuildStatus:
      Creating "Release\obj\binding\binding.tlog\unsuccessfulbuild" because "Always
      Create" was specified.
    ClCompile:
      C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe /c /I
      "C:\Users\GACHIO\.node-gyp\11.10.0\include\node" /I"C:\Users\GACHIO\.node-gyp
      \11.10.0\src" /I"C:\Users\GACHIO\.node-gyp\11.10.0\deps\openssl\config" /I"C:
      \Users\GACHIO\.node-gyp\11.10.0\deps\openssl\openssl\include" /I"C:\Users\GAC
      HIO\.node-gyp\11.10.0\deps\uv\include" /I"C:\Users\GACHIO\.node-gyp\11.10.0\d
      eps\zlib" /I"C:\Users\GACHIO\.node-gyp\11.10.0\deps\v8\include" /I..\..\nan /
      Z7 /nologo /W3 /WX- /MP /Ox /Ob2 /Oi /Ot /Oy /GL /D NODE_GYP_MODULE_NAME=bind
      ing /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D
       WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEP
      TIONS=0 /D BUILDING_NODE_EXTENSION /D _WINDLL /GF /Gm- /MT /GS /Gy /fp:precis
      e /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\binding\\" /Fd"Rel
      ease\obj\binding\vc140.pdb" /Gd /TP /wd4351 /wd4355 /wd4800 /wd4251 /wd4275 /
      wd4244 /wd4267 /errorReport:queue /Zc:threadSafeInit- ..\src\binding.cpp ..\s
      rc\create_string.cpp ..\src\custom_function_bridge.cpp ..\src\custom_importer
      _bridge.cpp ..\src\sass_context_wrapper.cpp ..\src\sass_types\boolean.cpp ..\
      src\sass_types\color.cpp ..\src\sass_types\error.cpp ..\src\sass_types\factor
      y.cpp ..\src\sass_types\list.cpp ..\src\sass_types\map.cpp ..\src\sass_types\
      null.cpp ..\src\sass_types\number.cpp ..\src\sass_types\string.cpp "C:\Users\
      GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\node-gyp\src\win_de
      lay_load_hook.cc"
      binding.cpp
      create_string.cpp
      custom_function_bridge.cpp
      custom_importer_bridge.cpp
    c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\sr
    c\custom_function_bridge.h(5): fatal error C1083: Cannot open include file: 'sa
    ss/values.h': No such file or directory (compiling source file ..\src\custom_fu
    nction_bridge.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_
    modules\node-sass\build\binding.vcxproj]
    c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\sr
    c\sass_context_wrapper.h(8): fatal error C1083: Cannot open include file: 'sass
    /context.h': No such file or directory (compiling source file ..\src\binding.cp
    p) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\node-sas
    s\build\binding.vcxproj]
    c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\sr
    c\custom_importer_bridge.h(5): fatal error C1083: Cannot open include file: 'sa
    ss/functions.h': No such file or directory (compiling source file ..\src\custom
    _importer_bridge.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\no
    de_modules\node-sass\build\binding.vcxproj]
      sass_context_wrapper.cpp
      boolean.cpp
      color.cpp
      error.cpp
    c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\sr
    c\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/val
    ues.h': No such file or directory (compiling source file ..\src\sass_types\colo
    r.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\node
    -sass\build\binding.vcxproj]
      factory.cpp
    c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\sr
    c\sass_context_wrapper.h(8): fatal error C1083: Cannot open include file: 'sass
    /context.h': No such file or directory (compiling source file ..\src\sass_conte
    xt_wrapper.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_mod
    ules\node-sass\build\binding.vcxproj]
      list.cpp
    c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\sr
    c\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/val
    ues.h': No such file or directory (compiling source file ..\src\sass_types\bool
    ean.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\no
    de-sass\build\binding.vcxproj]
      map.cpp
    c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\sr
    c\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/val
    ues.h': No such file or directory (compiling source file ..\src\sass_types\erro
    r.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\node
    -sass\build\binding.vcxproj]
      null.cpp
    c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\sr
    c\sass_types\factory.h(5): fatal error C1083: Cannot open include file: 'sass/v
    alues.h': No such file or directory (compiling source file ..\src\sass_types\fa
    ctory.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\
    node-sass\build\binding.vcxproj]
    c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\sr
    c\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/val
    ues.h': No such file or directory (compiling source file ..\src\sass_types\list
    .cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\node-
    sass\build\binding.vcxproj]
      number.cpp
      string.cpp
    c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\sr
    c\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/val
    ues.h': No such file or directory (compiling source file ..\src\sass_types\map.
    cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\node-s
    ass\build\binding.vcxproj]
      win_delay_load_hook.cc
    c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\sr
    c\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/val
    ues.h': No such file or directory (compiling source file ..\src\sass_types\null
    .cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\node-
    sass\build\binding.vcxproj]
    c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\sr
    c\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/val
    ues.h': No such file or directory (compiling source file ..\src\sass_types\stri
    ng.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\nod
    e-sass\build\binding.vcxproj]
    c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\sr
    c\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/val
    ues.h': No such file or directory (compiling source file ..\src\sass_types\numb
    er.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\nod
    e-sass\build\binding.vcxproj]
    Done Building Project "C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\no
    de_modules\node-sass\build\binding.vcxproj" (default targets) -- FAILED.
    
    Done Building Project "C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\no
    de_modules\node-sass\build\binding.sln" (default targets) -- FAILED.
    
    
    Build FAILED.
    
    "C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\b
    uild\binding.sln" (default target) (1) ->
    "C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass\b
    uild\binding.vcxproj" (default target) (2) ->
    (ClCompile target) ->
      c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\
    src\custom_function_bridge.h(5): fatal error C1083: Cannot open include file: '
    sass/values.h': No such file or directory (compiling source file ..\src\custom_
    function_bridge.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\nod
    e_modules\node-sass\build\binding.vcxproj]
      c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\
    src\sass_context_wrapper.h(8): fatal error C1083: Cannot open include file: 'sa
    ss/context.h': No such file or directory (compiling source file ..\src\binding.
    cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\node-s
    ass\build\binding.vcxproj]
      c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\
    src\custom_importer_bridge.h(5): fatal error C1083: Cannot open include file: '
    sass/functions.h': No such file or directory (compiling source file ..\src\cust
    om_importer_bridge.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\
    node_modules\node-sass\build\binding.vcxproj]
      c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\
    src\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/v
    alues.h': No such file or directory (compiling source file ..\src\sass_types\co
    lor.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\no
    de-sass\build\binding.vcxproj]
      c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\
    src\sass_context_wrapper.h(8): fatal error C1083: Cannot open include file: 'sa
    ss/context.h': No such file or directory (compiling source file ..\src\sass_con
    text_wrapper.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_m
    odules\node-sass\build\binding.vcxproj]
      c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\
    src\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/v
    alues.h': No such file or directory (compiling source file ..\src\sass_types\bo
    olean.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\
    node-sass\build\binding.vcxproj]
      c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\
    src\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/v
    alues.h': No such file or directory (compiling source file ..\src\sass_types\er
    ror.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\no
    de-sass\build\binding.vcxproj]
      c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\
    src\sass_types\factory.h(5): fatal error C1083: Cannot open include file: 'sass
    /values.h': No such file or directory (compiling source file ..\src\sass_types\
    factory.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_module
    s\node-sass\build\binding.vcxproj]
      c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\
    src\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/v
    alues.h': No such file or directory (compiling source file ..\src\sass_types\li
    st.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\nod
    e-sass\build\binding.vcxproj]
      c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\
    src\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/v
    alues.h': No such file or directory (compiling source file ..\src\sass_types\ma
    p.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\node
    -sass\build\binding.vcxproj]
      c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\
    src\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/v
    alues.h': No such file or directory (compiling source file ..\src\sass_types\nu
    ll.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\nod
    e-sass\build\binding.vcxproj]
      c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\
    src\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/v
    alues.h': No such file or directory (compiling source file ..\src\sass_types\st
    ring.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\n
    ode-sass\build\binding.vcxproj]
      c:\users\gachio\appdata\roaming\npm\node_modules\harp\node_modules\node-sass\
    src\sass_types\value.h(5): fatal error C1083: Cannot open include file: 'sass/v
    alues.h': No such file or directory (compiling source file ..\src\sass_types\nu
    mber.cpp) [C:\Users\GACHIO\AppData\Roaming\npm\node_modules\harp\node_modules\n
    ode-sass\build\binding.vcxproj]
    
        0 Warning(s)
        13 Error(s)
    
    Time Elapsed 00:00:06.86
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
    ed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Users\GACHIO\AppData\Roaming\npm\n
    ode_modules\harp\node_modules\node-gyp\lib\build.js:262:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
    s.js:254:12)
    gyp ERR! System Windows_NT 6.1.7601
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\GACHIO\\AppDa
    ta\\Roaming\\npm\\node_modules\\harp\\node_modules\\node-gyp\\bin\\node-gyp.js"
    "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
    "--libsass_library="
    gyp ERR! cwd C:.\AppData\Roaming\npm\node_modules\harp\node_modules\
    node-sass
    gyp ERR! node -v v11.10.0
    gyp ERR! node-gyp -v v3.8.0
    gyp ERR! not ok
    Build failed with error code: 1
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\har
    p\node_modules\fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
    1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
    )
    
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! node-sass@4.9.3 postinstall: `node scripts/build.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the node-sass@4.9.3 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional log
    ging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:.\AppData\Roaming\npm-cache\_logs\2019-02-23T07_01_14
    _008Z-debug.log
